vars:
  APP_ID:
    default: io.nlts.connect
  DISPLAY_NAME:
  VERSION:
    default: 1.0.0

platforms:
  ios:
    targets:
      App:
        bundleId: $APP_ID
        version: $VERSION
        displayName: $DISPLAY_NAME

  android:
    packageName: $APP_ID
    versionName: $VERSION
