vars:
  APP_ID:
    default: io.nlts.connect
  DISPLAY_NAME:
  VERSION:
    default: 1.0.0

platforms:
  ios:
    targets:
      App:
        bundleId: $APP_ID
        version: $VERSION
        incrementBuild: true
        displayName: $DISPLAY_NAME

        buildSettings:
          ENABLE_BITCODE: true
          STRIP_SWIFT_SYMBOLS: true

  android:
    packageName: $APP_ID
    versionName: $VERSION
    incrementVersionCode: true
