vars:
  APP_ID:
    default: io.ntls.connect
  DISPLAY_NAME:
    default: Nautilus Wallet
  VERSION:
    default: 1.0.0
  BUILD_NUMBER:
    default: 1

platforms:
  ios:
    targets:
      App:
        bundleId: $APP_ID
        version: $VERSION
        buildNumber: $BUILD_NUMBER
        displayName: $DISPLAY_NAME
        productName: $DISPLAY_NAME
        buildSettings:
          ENABLE_BITCODE: false
          STRIP_SWIFT_SYMBOLS: true

  android:
    packageName: $APP_ID
    versionName: $VERSION
    versionCode: $BUILD_NUMBER
    appName: $DISPLAY_NAME
